site_name: macro
repo_url: https://github.com/externref/macro
site_description: ASGI webserver in python
site_author: externref
copyright: Copyright externref ( 2025 - present )
site_url: https://externref.github.io/macro

theme:
  name: "material"

  font:
    text: Ubuntu

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.tabs.link

  palette:

    - scheme: light
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            merge_init_into_class: false
            inherited_members: true
          inventories:
            - https://docs.python.org/3.9/objects.inv

  - search
  # - social:
  #     cards_color:
  #       fill: "#3761A3" 
  #       text: "#FFFFFF"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - home: index.md
  - API Reference:
    - api/server.md
    - api/request.md
    - api/response.md
    
